version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@2

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/lint:
          name: lint
      - kitchen/dokken-single:
          name: centos-7
          platform: centos-7
          suite: server-install
          requires: [  danger, lint ]
      - kitchen/dokken-single:
          name: debian-9
          platform: debian-9
          suite: server-install
          requires: [  danger, lint ]
      - kitchen/dokken-single:
          name: ubuntu-16.04
          platform: ubuntu-1604
          suite: server-install
          requires: [  danger, lint ]
      - kitchen/dokken-single:
          name: ubuntu-18.04
          platform: ubuntu-1804
          suite: server-install
          requires: [  danger, lint ]
